version: 2
build:
  os: "ubuntu-22.04"
  tools:
    nodejs: "20"
  jobs:
    install:
      - npm install vitepress
    build:
      html:
        - npm run docs:build
        - cp ./docs/img/favicon.png ./docs/.vitepress/dist/
        - mkdir $READTHEDOCS_OUTPUT
        - mv ./docs/.vitepress/dist $READTHEDOCS_OUTPUT/html
