version: 2
build:
  os: "ubuntu-22.04"
  tools:
    nodejs: "20"
  jobs:
    install:
      - npm install vitepress
    build:
      html:
        - npm run docs:build
        - ls $READTHEDOCS_OUTPUT
        - cp -R ./docs/.vitepress/dist/* $READTHEDOCS_OUTPUT/html/
